services:
  db:
    image: postgres:16.4-bullseye
    container_name: transc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432
    networks:
      - transc_network

  web:
    build: ./transc_api
    image: transc_web
    container_name: transc_web
    volumes:
      - ./transc_api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_HOST: ${DJANGO_HOST}
      DEBUG: ${DEBUG}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    networks:
      - transc_network

volumes:
  postgres_data:
    name: postgres_data

networks:
  transc_network:
    name: transc_network
    driver: bridge