services:
  back:
    build: ./tmpbackend
    ports:
      - '8000:8000'
  frontend:
    build: ./frontend
    ports:
      - '443:443'
    volumes:
      - front:/var/www/html

volumes:
  front:
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: ~/volumes # change for local machine

  postgres_data:
    name: postgres_data

networks:
  transc_network:
    name: transc_network
    driver: bridge
